export const LANGUAGES = [
  { id: "fr", title: "Français" },
  { id: "en", title: "English" },
  { id: "es", title: "Español" },
  { id: "de", title: "Deutsch" },
] as const

// Keep in sync with FONT_CHOICES in apps/web/src/lib/settings.ts
export const FONT_CHOICES = [
  "Inter",
  "Nunito",
  "Fredoka",
  "Baloo 2",
  "Poppins",
  "Outfit",
  "DM Sans",
  "Montserrat",
  "Space Grotesk",
  "Lilita One",
  "Bangers",
  "Bebas Neue",
  "Cinzel",
  "Playfair Display",
  "Alegreya",
  "Press Start 2P",
] as const

/**
 * Libellés d'interface communs à tous les jeux, modifiables dans Sanity (document « Texts », onglet « Interface »).
 * `fr` = valeur par défaut. Variables entre accolades : {code}, {name}, {count}, {max}.
 */
export const UI_TEXTS = [
  // Accueil
  { key: "nicknamePlaceholder", group: "home", title: "Nickname placeholder", fr: "VOTRE PSEUDO…" },
  { key: "createButton", group: "home", title: "Create button", fr: "Créer une partie" },
  { key: "joinButton", group: "home", title: "Join button (code typed)", fr: "Rejoindre la partie" },
  { key: "chooseNickname", group: "home", title: "Error: no nickname", fr: "Choisissez d'abord votre pseudo." },
  { key: "codeLength", group: "home", title: "Error: code length", fr: "Le code de partie fait 6 caractères." },
  { key: "linkCopied", group: "home", title: "Toast: link copied", fr: "Lien de la partie copié !" },
  { key: "linkCopiedHint", group: "home", title: "Toast: link copied (detail)", fr: "Envoyez-le à vos amis pour qu'ils vous rejoignent." },
  { key: "gameCreated", group: "home", title: "Toast: game created", fr: "Partie {code} créée !" },
  { key: "codeLabel", group: "home", title: "Code field label", fr: "Code de la partie" },
  { key: "copyLink", group: "home", title: "Copy link button", fr: "Copier le lien de la partie" },
  { key: "feedbackButton", group: "home", title: "Feedback: button", fr: "Envoyer un feedback" },
  { key: "feedbackTitle", group: "home", title: "Feedback: title", fr: "Votre feedback" },
  { key: "feedbackType", group: "home", title: "Feedback: type label", fr: "Type de retour" },
  { key: "feedbackTypeReview", group: "home", title: "Feedback: type Review", fr: "Envoyer un avis" },
  { key: "feedbackTypeBug", group: "home", title: "Feedback: type Bug", fr: "Signaler un bug" },
  { key: "feedbackTypeSuggestion", group: "home", title: "Feedback: type Suggestion", fr: "Suggestion d'amélioration" },
  { key: "feedbackTypeOther", group: "home", title: "Feedback: type Other", fr: "Autres" },
  { key: "feedbackPlaceholder", group: "home", title: "Feedback: message placeholder", fr: "Ce qui vous plaît, ce qui coince, une idée…" },
  { key: "feedbackEmail", group: "home", title: "Feedback: email placeholder", fr: "Votre e-mail (facultatif, pour vous répondre)" },
  { key: "feedbackScreenshotAdd", group: "home", title: "Feedback: add screenshot", fr: "Ajouter une capture d'écran" },
  { key: "feedbackScreenshotRemove", group: "home", title: "Feedback: remove screenshot", fr: "Retirer la capture" },
  { key: "feedbackSend", group: "home", title: "Feedback: send button", fr: "Envoyer" },
  { key: "feedbackThanks", group: "home", title: "Feedback: thanks", fr: "Merci, votre message est bien arrivé !" },
  // Invitation et lobby
  { key: "joinGameButton", group: "lobby", title: "Join button (invitation)", fr: "Rejoindre la partie" },
  { key: "gameNotFound", group: "lobby", title: "Game not found", fr: "Cette partie est introuvable. Vérifiez le code {code} ou créez-en une nouvelle." },
  { key: "alreadyStarted", group: "lobby", title: "Game already started", fr: "Cette partie a déjà commencé." },
  { key: "backHome", group: "lobby", title: "Back home button", fr: "Retour à l'accueil" },
  { key: "shareInvite", group: "lobby", title: "Lobby: share invite", fr: "Partagez le code ou le lien de la partie à vos amis." },
  { key: "playerCount", group: "lobby", title: "Lobby: player count", fr: "{count}/{max} joueurs" },
  { key: "you", group: "lobby", title: "Lobby: (you)", fr: "(vous)" },
  { key: "host", group: "lobby", title: "Lobby: host label", fr: "Hôte" },
  { key: "startButton", group: "lobby", title: "Start button (host)", fr: "Lancer la partie" },
  { key: "waitingPlayers", group: "lobby", title: "Start button: not enough players", fr: "En attente de joueurs…" },
  { key: "waitingHost", group: "lobby", title: "Waiting for host", fr: "En attente de l'hôte" },
  // En partie
  { key: "yourTurn", group: "game", title: "Your turn", fr: "C'est votre tour" },
  { key: "turnOf", group: "game", title: "Turn of a player", fr: "Au tour de {name}" },
  { key: "yourTurnShort", group: "game", title: "History: your turn", fr: "Votre tour" },
  { key: "turnOfShort", group: "game", title: "History: turn of a player", fr: "Tour de {name}" },
  { key: "waiting", group: "game", title: "Waiting (no active player)", fr: "La partie se prépare…" },
  { key: "gameOver", group: "game", title: "Game over (ticker)", fr: "Fin de la partie" },
  { key: "leave", group: "game", title: "Leave button", fr: "Quitter" },
  { key: "takeoverPrompt", group: "game", title: "Absent player: prompt", fr: "{name} ne répond plus ?" },
  { key: "takeoverButton", group: "game", title: "Absent player: button", fr: "Jouer à sa place" },
  { key: "replay", group: "game", title: "Replay button", fr: "Rejouer" },
  { key: "winnerTitle", group: "game", title: "Scoreboard: above the winner", fr: "Victoire de" },
  { key: "showScores", group: "game", title: "Scoreboard: show", fr: "Afficher le tableau des scores" },
  { key: "hideScores", group: "game", title: "Scoreboard: hide", fr: "Masquer le tableau des scores" },
  { key: "shareResult", group: "game", title: "Scoreboard: share", fr: "Partager le résultat" },
  { key: "desktopOnly", group: "game", title: "Desktop only message", fr: "Ce jeu se joue sur ordinateur : agrandissez la fenêtre ou revenez depuis un écran plus large." },
  { key: "creditsAdaptation", group: "home", title: "Footer: adaptation", fr: "Adaptation en ligne non officielle et gratuite de" },
  { key: "creditsBy", group: "home", title: "Footer: “a game by”", fr: "un jeu de" },
  { key: "creditsPublishedBy", group: "home", title: "Footer: “published by”", fr: "et édité par" },
  { key: "creditsRights", group: "home", title: "Footer: rights", fr: "Tous droits réservés à leurs auteurs." },
  { key: "creditsRightsPublisher", group: "home", title: "Footer: rights (with publisher)", fr: "Tous droits réservés à leurs auteurs et à l’éditeur." },
  { key: "developedBy", group: "home", title: "Footer: developed by", fr: "Développé par" },
  { key: "claims", group: "home", title: "Footer: claims", fr: "Pour toute réclamation :" },
  { key: "soundSettings", group: "home", title: "Sound menu: button", fr: "Réglages du son" },
  { key: "soundTitle", group: "home", title: "Sound menu: title", fr: "Son" },
  { key: "soundMusic", group: "home", title: "Sound menu: music", fr: "Musique" },
  { key: "soundAmbience", group: "home", title: "Sound menu: ambience", fr: "Ambiance" },
  { key: "soundEffects", group: "home", title: "Sound menu: effects", fr: "Effets sonores" },
  { key: "soundAlerts", group: "home", title: "Sound menu: alerts", fr: "Alertes" },
  { key: "soundReactions", group: "home", title: "Sound menu: reactions", fr: "Réactions" },
  { key: "soundTrack", group: "home", title: "Sound menu: music track", fr: "Morceau" },
  { key: "soundOn", group: "home", title: "Sound button: turn on", fr: "Activer le son" },
  { key: "soundOff", group: "home", title: "Sound button: turn off", fr: "Couper le son" },
  { key: "language", group: "home", title: "Language selector label", fr: "Langue" },
  { key: "menu", group: "home", title: "Settings menu: open", fr: "Menu" },
  { key: "closeMenu", group: "home", title: "Settings menu: close", fr: "Fermer le menu" },
  { key: "gameSettingsMenu", group: "home", title: "Menu: game settings entry", fr: "Configuration de la partie" },
  { key: "gameSettingsStandard", group: "home", title: "Game settings: default configuration", fr: "Partie standard" },
  { key: "gameSettingsNone", group: "home", title: "Game settings: nothing configurable", fr: "Cette partie n'a aucune option." },
  { key: "gameSettingsOn", group: "home", title: "Game settings: extension on", fr: "Activée" },
  { key: "gameSettingsOff", group: "home", title: "Game settings: extension off", fr: "Désactivée" },
  { key: "cookiesMenu", group: "home", title: "Menu: cookies entry", fr: "Cookies" },
  { key: "cookiesBody", group: "home", title: "Cookies: text (blank line = new paragraph)", fr: "Ce jeu n'utilise aucun cookie publicitaire et ne te suit pas d'un site à l'autre.\n\nSeuls des traceurs nécessaires au fonctionnement sont utilisés : un cookie d'identité de joueur pour te reconnaître dans ta partie, un cookie de langue, et le stockage local de ton navigateur (pseudo, préférences de son).\n\nLes éventuelles mesures d'audience sont anonymes et n'utilisent pas de cookie." },
  { key: "legalMenu", group: "home", title: "Menu: legal entry", fr: "Mentions légales" },
  { key: "legalBody", group: "home", title: "Legal: text ({publisher}, {authors}, {contact}; blank line = new paragraph)", fr: "Éditeur : {publisher}\nAuteur : {authors}\nContact : {contact}\n\nHébergement : Vercel Inc. (vercel.com).\n\nLes noms, marques et univers des jeux de société cités appartiennent à leurs ayants droit. Ce site est une adaptation en ligne sans but d'usurpation." },
  { key: "chat", group: "game", title: "Chat: title", fr: "Chat" },
  { key: "chatPlaceholder", group: "game", title: "Chat: input placeholder", fr: "Écrire un message…" },
  { key: "chatSend", group: "game", title: "Chat: send button", fr: "Envoyer" },
  { key: "chatReactions", group: "game", title: "Chat: reactions button", fr: "Réactions" },
  { key: "chatEmpty", group: "game", title: "Chat: no message yet", fr: "Aucun message pour l’instant" },
  { key: "rules", group: "home", title: "Rules: title", fr: "Règles" },
  { key: "rulesTitle", group: "home", title: "Rules: button label", fr: "Règles du jeu" },
  { key: "rulesVideo", group: "home", title: "Rules: video tab", fr: "Vidéo" },
  { key: "rulesPdf", group: "home", title: "Rules: PDF link", fr: "Règles PDF ({lang})" },
  { key: "rulesVideoTitle", group: "home", title: "Rules: video title", fr: "Règles en vidéo" },
  { key: "gameOptions", group: "lobby", title: "Lobby: game options", fr: "Options de la partie" },
  { key: "gameParameters", group: "lobby", title: "Lobby: parameters section", fr: "Paramètres" },
  { key: "gameExtensions", group: "lobby", title: "Lobby: extensions section", fr: "Extensions" },
  { key: "gamePresets", group: "lobby", title: "Lobby: presets", fr: "Préréglages" },
  { key: "optionNeeds", group: "lobby", title: "Lobby: option needs another ({names})", fr: "Nécessite : {names}" },
  { key: "optionConflicts", group: "lobby", title: "Lobby: option conflicts ({names})", fr: "Incompatible avec : {names}" },
  { key: "optionPlayers", group: "lobby", title: "Lobby: option unavailable for this player count", fr: "Indisponible avec {count} joueurs" },
  { key: "chosenByHost", group: "lobby", title: "Lobby: options chosen by the host", fr: "choisies par l'hôte" },
  { key: "resultAlt", group: "game", title: "Share: image description", fr: "Résultat de la partie" },
  { key: "copyImage", group: "game", title: "Share: copy image", fr: "Copier l'image" },
  { key: "download", group: "game", title: "Share: download", fr: "Télécharger" },
  { key: "imageCopied", group: "game", title: "Share: toast copied", fr: "Image copiée, il ne reste plus qu'à la coller" },
  { key: "imageError", group: "game", title: "Share: toast error", fr: "Impossible de générer l'image du résultat" },
  { key: "share", group: "game", title: "Share: share button", fr: "Partager" },
  { key: "copyFailed", group: "game", title: "Share: copy failed", fr: "Impossible de copier l'image" },
  { key: "shareFailed", group: "game", title: "Share: share failed", fr: "Impossible de partager l'image" },
  { key: "missionsWaiting", group: "game", title: "Opening: waiting for other players", fr: "En attente des autres joueurs ({read}/{total})" },
  { key: "missionsSkipPrompt", group: "game", title: "Opening: players still reading (prompt, {names} = who)", fr: "En attente de {names}…" },
  { key: "missionsSkipButton", group: "game", title: "Opening: start without waiting (button)", fr: "Commencer sans attendre" },
  { key: "winsWith", group: "game", title: "Share: text", fr: "{names} remporte la partie avec {points} points !" },
] as const

export type UiTextKey = (typeof UI_TEXTS)[number]["key"]
export const UI_TEXT_GROUPS = [
  { name: "home", title: "Home" },
  { name: "lobby", title: "Invitation & lobby" },
  { name: "game", title: "In game" },
] as const
