/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type LocaleStringList = {
  _type: "localeStringList";
  fr?: Array<string>;
  en?: Array<string>;
};

export type LocaleText = {
  _type: "localeText";
  fr?: string;
  en?: string;
};

export type LocaleString = {
  _type: "localeString";
  fr?: string;
  en?: string;
};

export type Condition = {
  _type: "condition";
  type?:
    | "statutFamille"
    | "nombreFamillesStatut"
    | "nombreCartesDomaine"
    | "nombreCartesTable"
    | "comparaisonJoueurs"
    | "et"
    | "ou"
    | "non";
  family?: "papillon" | "crapaud" | "rossignol" | "lievre" | "cerf" | "carpe";
  status?: "lumiere" | "disgrace" | "neutre";
  familyFilter?:
    "papillon" | "crapaud" | "rossignol" | "lievre" | "cerf" | "carpe";
  roleFilter?: "noble" | "espion" | "assassin" | "garde" | "sansRole";
  level?: "haut" | "bas";
  comparator?: "gte" | "lte" | "eq" | "gt" | "lt";
  value?: number;
  opponent?:
    | "voisinGauche"
    | "voisinDroite"
    | "tousLesAdversaires"
    | "auMoinsUnAdversaire";
  mode?: "cartes" | "poids";
  conditions?: Array<
    {
      _key: string;
    } & Condition
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Mission = {
  _id: string;
  _type: "mission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  color?: "blanche" | "bleue";
  text?: LocaleText;
  card?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  condition?: Condition;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type FamilyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "family";
};

export type RoleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "role";
};

export type Courtier = {
  _id: string;
  _type: "courtier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  family?: FamilyReference;
  role?: RoleReference;
  card?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quantity?: number;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  key?: "noble" | "espion" | "assassin" | "garde";
  countPerFamily?: number;
  pictogram?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  lettering?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rule?: LocaleText;
};

export type Family = {
  _id: string;
  _type: "family";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  key?: "papillon" | "crapaud" | "rossignol" | "lievre" | "cerf" | "carpe";
  color?: string;
  pictogram?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Texts = {
  _id: string;
  _type: "texts";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  missionsButton?: LocaleString;
  guestsSettling?: LocaleString;
  banquetStarts?: LocaleString;
  winnerPhrases?: LocaleStringList;
};

export type Rules = {
  _id: string;
  _type: "rules";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  videoId?: string;
  videoTitle?: LocaleString;
  goalTitle?: LocaleString;
  goalIntro?: LocaleText;
  goalFamilies?: LocaleText;
  goalMissions?: LocaleText;
  flowTitle?: LocaleString;
  flowIntro?: LocaleText;
  flowMat?: LocaleText;
  flowHand?: LocaleText;
  flowMissions?: LocaleText;
  flowStart?: LocaleText;
  turnTitle?: LocaleString;
  turnIntro?: LocaleText;
  turnTable?: LocaleText;
  turnDomain?: LocaleText;
  turnOpponent?: LocaleText;
  turnEnd?: LocaleText;
  rolesTitle?: LocaleString;
  rolesIntro?: LocaleText;
  scoringTitle?: LocaleString;
  scoringIntro?: LocaleText;
  scoringReveal?: LocaleText;
  scoringStatus?: LocaleText;
  scoringPoints?: LocaleText;
};

export type Game = {
  _id: string;
  _type: "game";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mat?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  matTexture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decorations?: Array<{
    name?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "decoration";
    _key: string;
  }>;
  courtierBack?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  whiteMissionBack?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blueMissionBack?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Interface = {
  _id: string;
  _type: "interface";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  banquetTop?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  banquetBottom?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  queen?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  pattern?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  paper?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  pictogramFrame?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | LocaleStringList
  | LocaleText
  | LocaleString
  | Condition
  | SanityImageAssetReference
  | Mission
  | SanityImageCrop
  | SanityImageHotspot
  | FamilyReference
  | RoleReference
  | Courtier
  | Role
  | Family
  | Texts
  | Rules
  | Game
  | Interface
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/sanity/queries.ts
// Variable: CATALOGUE_QUERY
// Query: {  "interface": *[_id == "interface"][0]{ logo, banquetTop, banquetBottom, queen, pattern, paper, pictogramFrame },  "game": *[_id == "game"][0]{ mat, matTexture, courtierBack, whiteMissionBack, blueMissionBack },  "rules": *[_id == "rules"][0],  "texts": *[_id == "texts"][0]{ missionsButton, guestsSettling, banquetStarts, winnerPhrases },  "families": *[_type == "family"]{ _id, name, key, color, pictogram },  "roles": *[_type == "role"]{ _id, name, key, countPerFamily, pictogram, rule, "lettering": lettering.asset->url },  "courtiers": *[_type == "courtier"]{ _id, quantity, card, "family": family->key, "role": role->key },  "missions": *[_type == "mission"]{ _id, color, text, card, condition }}
export type CATALOGUE_QUERY_RESULT = {
  interface:
    | {
        logo: null;
        banquetTop: null;
        banquetBottom: null;
        queen: null;
        pattern: null;
        paper: null;
        pictogramFrame: null;
      }
    | {
        logo: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        banquetTop: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        banquetBottom: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        queen: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        pattern: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        paper: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        pictogramFrame: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | null;
  game:
    | {
        mat: null;
        matTexture: null;
        courtierBack: null;
        whiteMissionBack: null;
        blueMissionBack: null;
      }
    | {
        mat: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        matTexture: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        courtierBack: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        whiteMissionBack: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        blueMissionBack: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | null;
  rules:
    | {
        _id: "rules";
        _type: "courtier";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        family?: FamilyReference;
        role?: RoleReference;
        card?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        quantity?: number;
      }
    | {
        _id: "rules";
        _type: "family";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: LocaleString;
        key?:
          "carpe" | "cerf" | "crapaud" | "lievre" | "papillon" | "rossignol";
        color?: string;
        pictogram?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _id: "rules";
        _type: "game";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        mat?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        matTexture?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        decorations?: Array<{
          name?: string;
          image?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          _type: "decoration";
          _key: string;
        }>;
        courtierBack?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        whiteMissionBack?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        blueMissionBack?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _id: "rules";
        _type: "interface";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        logo?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        banquetTop?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        banquetBottom?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        queen?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        pattern?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        paper?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        pictogramFrame?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _id: "rules";
        _type: "mission";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        color?: "blanche" | "bleue";
        text?: LocaleText;
        card?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        condition?: Condition;
      }
    | {
        _id: "rules";
        _type: "role";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: LocaleString;
        key?: "assassin" | "espion" | "garde" | "noble";
        countPerFamily?: number;
        pictogram?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        lettering?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        rule?: LocaleText;
      }
    | {
        _id: "rules";
        _type: "rules";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        videoId?: string;
        videoTitle?: LocaleString;
        goalTitle?: LocaleString;
        goalIntro?: LocaleText;
        goalFamilies?: LocaleText;
        goalMissions?: LocaleText;
        flowTitle?: LocaleString;
        flowIntro?: LocaleText;
        flowMat?: LocaleText;
        flowHand?: LocaleText;
        flowMissions?: LocaleText;
        flowStart?: LocaleText;
        turnTitle?: LocaleString;
        turnIntro?: LocaleText;
        turnTable?: LocaleText;
        turnDomain?: LocaleText;
        turnOpponent?: LocaleText;
        turnEnd?: LocaleText;
        rolesTitle?: LocaleString;
        rolesIntro?: LocaleText;
        scoringTitle?: LocaleString;
        scoringIntro?: LocaleText;
        scoringReveal?: LocaleText;
        scoringStatus?: LocaleText;
        scoringPoints?: LocaleText;
      }
    | {
        _id: "rules";
        _type: "sanity.fileAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "rules";
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "rules";
        _type: "texts";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        missionsButton?: LocaleString;
        guestsSettling?: LocaleString;
        banquetStarts?: LocaleString;
        winnerPhrases?: LocaleStringList;
      }
    | null;
  texts:
    | {
        missionsButton: null;
        guestsSettling: null;
        banquetStarts: null;
        winnerPhrases: null;
      }
    | {
        missionsButton: LocaleString | null;
        guestsSettling: LocaleString | null;
        banquetStarts: LocaleString | null;
        winnerPhrases: LocaleStringList | null;
      }
    | null;
  families: Array<{
    _id: string;
    name: LocaleString | null;
    key:
      "carpe" | "cerf" | "crapaud" | "lievre" | "papillon" | "rossignol" | null;
    color: string | null;
    pictogram: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
  roles: Array<{
    _id: string;
    name: LocaleString | null;
    key: "assassin" | "espion" | "garde" | "noble" | null;
    countPerFamily: number | null;
    pictogram: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    rule: LocaleText | null;
    lettering: string | null;
  }>;
  courtiers: Array<{
    _id: string;
    quantity: number | null;
    card: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    family:
      "carpe" | "cerf" | "crapaud" | "lievre" | "papillon" | "rossignol" | null;
    role: "assassin" | "espion" | "garde" | "noble" | null;
  }>;
  missions: Array<{
    _id: string;
    color: "blanche" | "bleue" | null;
    text: LocaleText | null;
    card: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    condition: Condition | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "interface": *[_id == "interface"][0]{ logo, banquetTop, banquetBottom, queen, pattern, paper, pictogramFrame },\n  "game": *[_id == "game"][0]{ mat, matTexture, courtierBack, whiteMissionBack, blueMissionBack },\n  "rules": *[_id == "rules"][0],\n  "texts": *[_id == "texts"][0]{ missionsButton, guestsSettling, banquetStarts, winnerPhrases },\n  "families": *[_type == "family"]{ _id, name, key, color, pictogram },\n  "roles": *[_type == "role"]{ _id, name, key, countPerFamily, pictogram, rule, "lettering": lettering.asset->url },\n  "courtiers": *[_type == "courtier"]{ _id, quantity, card, "family": family->key, "role": role->key },\n  "missions": *[_type == "mission"]{ _id, color, text, card, condition }\n}': CATALOGUE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
