/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Condition = {
  _type: "condition";
  type?:
    | "statutFamille"
    | "nombreFamillesStatut"
    | "nombreCartesDomaine"
    | "nombreCartesTable"
    | "comparaisonJoueurs"
    | "et"
    | "ou"
    | "non";
  famille?: "papillon" | "crapaud" | "rossignol" | "lievre" | "cerf" | "carpe";
  statut?: "lumiere" | "disgrace" | "neutre";
  filtreFamille?:
    "papillon" | "crapaud" | "rossignol" | "lievre" | "cerf" | "carpe";
  filtreRole?: "noble" | "espion" | "assassin" | "garde" | "sansRole";
  niveau?: "haut" | "bas";
  comparateur?: "gte" | "lte" | "eq" | "gt" | "lt";
  valeur?: number;
  adversaire?:
    | "voisinGauche"
    | "voisinDroite"
    | "tousLesAdversaires"
    | "auMoinsUnAdversaire";
  mode?: "cartes" | "poids";
  conditions?: Array<
    {
      _key: string;
    } & Condition
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Mission = {
  _id: string;
  _type: "mission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  couleur?: "blanche" | "bleue";
  texte?: string;
  carte?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  condition?: Condition;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type FamilleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "famille";
};

export type RoleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "role";
};

export type Courtisan = {
  _id: string;
  _type: "courtisan";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  famille?: FamilleReference;
  role?: RoleReference;
  carte?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quantite?: number;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  cle?: "noble" | "espion" | "assassin" | "garde";
  picto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Famille = {
  _id: string;
  _type: "famille";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nom?: string;
  cle?: "papillon" | "crapaud" | "rossignol" | "lievre" | "cerf" | "carpe";
  couleur?: string;
  picto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Textes = {
  _id: string;
  _type: "textes";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  phrasesVainqueur?: Array<string>;
};

export type Rules = {
  _id: string;
  _type: "rules";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  missions?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noble?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  garde?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  espion?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  assassin?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  table?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  exempleEspion?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  exempleAssassin?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decompteTable?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decompteDomaine?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Board = {
  _id: string;
  _type: "board";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tapis?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decorations?: Array<{
    nom?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "decoration";
    _key: string;
  }>;
};

export type Assets = {
  _id: string;
  _type: "assets";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  dosCourtisan?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  dosMissionBlanche?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  dosMissionBleue?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  banquetHaut?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  banquetBas?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Condition
  | SanityImageAssetReference
  | Mission
  | SanityImageCrop
  | SanityImageHotspot
  | FamilleReference
  | RoleReference
  | Courtisan
  | Role
  | Famille
  | Textes
  | Rules
  | Board
  | Assets
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/sanity/queries.ts
// Variable: CATALOGUE_QUERY
// Query: {  "assets": *[_id == "assets"][0]{ logo, dosCourtisan, dosMissionBlanche, dosMissionBleue, banquetHaut, banquetBas },  "board": *[_id == "board"][0]{ tapis },  "rules": *[_id == "rules"][0]{ missions, noble, garde, espion, assassin, table, exempleEspion, exempleAssassin, decompteTable, decompteDomaine },  "textes": *[_id == "textes"][0]{ phrasesVainqueur },  "familles": *[_type == "famille"]{ _id, nom, cle, couleur, picto },  "roles": *[_type == "role"]{ _id, nom, cle, picto },  "courtisans": *[_type == "courtisan"]{ _id, quantite, carte, "famille": famille->cle, "role": role->cle },  "missions": *[_type == "mission"]{ _id, couleur, texte, carte, condition }}
export type CATALOGUE_QUERY_RESULT = {
  assets:
    | {
        logo: null;
        dosCourtisan: null;
        dosMissionBlanche: null;
        dosMissionBleue: null;
        banquetHaut: null;
        banquetBas: null;
      }
    | {
        logo: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        dosCourtisan: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        dosMissionBlanche: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        dosMissionBleue: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        banquetHaut: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        banquetBas: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | null;
  board:
    | {
        tapis: null;
      }
    | {
        tapis: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | null;
  rules:
    | {
        missions: null;
        noble: null;
        garde: null;
        espion: null;
        assassin: null;
        table: null;
        exempleEspion: null;
        exempleAssassin: null;
        decompteTable: null;
        decompteDomaine: null;
      }
    | {
        missions: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noble: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        garde: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        espion: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        assassin: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        table: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        exempleEspion: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        exempleAssassin: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        decompteTable: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        decompteDomaine: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | null;
  textes:
    | {
        phrasesVainqueur: null;
      }
    | {
        phrasesVainqueur: Array<string> | null;
      }
    | null;
  familles: Array<{
    _id: string;
    nom: string | null;
    cle:
      "carpe" | "cerf" | "crapaud" | "lievre" | "papillon" | "rossignol" | null;
    couleur: string | null;
    picto: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
  roles: Array<{
    _id: string;
    nom: string | null;
    cle: "assassin" | "espion" | "garde" | "noble" | null;
    picto: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
  courtisans: Array<{
    _id: string;
    quantite: number | null;
    carte: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    famille:
      "carpe" | "cerf" | "crapaud" | "lievre" | "papillon" | "rossignol" | null;
    role: "assassin" | "espion" | "garde" | "noble" | null;
  }>;
  missions: Array<{
    _id: string;
    couleur: "blanche" | "bleue" | null;
    texte: string | null;
    carte: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    condition: Condition | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "assets": *[_id == "assets"][0]{ logo, dosCourtisan, dosMissionBlanche, dosMissionBleue, banquetHaut, banquetBas },\n  "board": *[_id == "board"][0]{ tapis },\n  "rules": *[_id == "rules"][0]{ missions, noble, garde, espion, assassin, table, exempleEspion, exempleAssassin, decompteTable, decompteDomaine },\n  "textes": *[_id == "textes"][0]{ phrasesVainqueur },\n  "familles": *[_type == "famille"]{ _id, nom, cle, couleur, picto },\n  "roles": *[_type == "role"]{ _id, nom, cle, picto },\n  "courtisans": *[_type == "courtisan"]{ _id, quantite, carte, "famille": famille->cle, "role": role->cle },\n  "missions": *[_type == "mission"]{ _id, couleur, texte, carte, condition }\n}': CATALOGUE_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
