/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Condition = {
  _type: "condition";
  type?:
    | "familyStatus"
    | "familiesWithStatus"
    | "domainCards"
    | "tableCards"
    | "playerComparison"
    | "and"
    | "or"
    | "not";
  family?: "butterfly" | "toad" | "nightingale" | "hare" | "stag" | "carp";
  status?: "light" | "disgrace" | "neutral";
  familyFilter?:
    "butterfly" | "toad" | "nightingale" | "hare" | "stag" | "carp";
  roleFilter?: "noble" | "spy" | "assassin" | "guard" | "noRole";
  level?: "up" | "down";
  comparator?: "gte" | "lte" | "eq" | "gt" | "lt";
  value?: number;
  opponent?: "leftNeighbor" | "rightNeighbor" | "allOpponents" | "anyOpponent";
  mode?: "cards" | "weight";
  conditions?: Array<
    {
      _key: string;
    } & Condition
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Mission = {
  _id: string;
  _type: "mission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  color?: "white" | "blue";
  text?: LocaleText;
  card?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  condition?: Condition;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type LocaleText = {
  _type: "localeText";
  fr?: string;
  en?: string;
};

export type FamilyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "family";
};

export type RoleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "role";
};

export type Courtier = {
  _id: string;
  _type: "courtier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  family?: FamilyReference;
  role?: RoleReference;
  card?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quantity?: number;
};

export type Role = {
  _id: string;
  _type: "role";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  key?: "noble" | "spy" | "assassin" | "guard";
  countPerFamily?: number;
  pictogram?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  lettering?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rule?: LocaleText;
};

export type LocaleString = {
  _type: "localeString";
  fr?: string;
  en?: string;
};

export type Family = {
  _id: string;
  _type: "family";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocaleString;
  key?: "butterfly" | "toad" | "nightingale" | "hare" | "stag" | "carp";
  color?: string;
  pictogram?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Texts = {
  _id: string;
  _type: "texts";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagline?: LocaleString;
  homeTitle?: LocaleString;
  homeIntro?: LocaleText;
  victoryPhrases?: LocaleStringList;
  ui_home?: {
    nicknamePlaceholder?: LocaleString;
    createButton?: LocaleString;
    joinButton?: LocaleString;
    chooseNickname?: LocaleString;
    codeLength?: LocaleString;
    linkCopied?: LocaleString;
    linkCopiedHint?: LocaleString;
    gameCreated?: LocaleString;
    codeLabel?: LocaleString;
    copyLink?: LocaleString;
  };
  ui_lobby?: {
    joinGameButton?: LocaleString;
    gameNotFound?: LocaleString;
    alreadyStarted?: LocaleString;
    backHome?: LocaleString;
    shareInvite?: LocaleString;
    playerCount?: LocaleString;
    you?: LocaleString;
    host?: LocaleString;
    startButton?: LocaleString;
    waitingPlayers?: LocaleString;
    waitingHost?: LocaleString;
  };
  ui_game?: {
    yourTurn?: LocaleString;
    turnOf?: LocaleString;
    yourTurnShort?: LocaleString;
    turnOfShort?: LocaleString;
    waiting?: LocaleString;
    gameOver?: LocaleString;
    leave?: LocaleString;
    replay?: LocaleString;
    desktopOnly?: LocaleString;
  };
  missionsButton?: LocaleString;
  banquetStarts?: LocaleString;
};

export type LocaleStringList = {
  _type: "localeStringList";
  fr?: Array<string>;
  en?: Array<string>;
};

export type Rules = {
  _id: string;
  _type: "rules";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  videoId?: string;
  videoTitle?: LocaleString;
  goalTitle?: LocaleString;
  goalIntro?: LocaleText;
  goalFamilies?: LocaleText;
  goalMissions?: LocaleText;
  flowTitle?: LocaleString;
  flowIntro?: LocaleText;
  flowMat?: LocaleText;
  flowHand?: LocaleText;
  flowMissions?: LocaleText;
  flowStart?: LocaleText;
  turnTitle?: LocaleString;
  turnIntro?: LocaleText;
  turnTable?: LocaleText;
  turnDomain?: LocaleText;
  turnOpponent?: LocaleText;
  turnEnd?: LocaleText;
  rolesTitle?: LocaleString;
  rolesIntro?: LocaleText;
  scoringTitle?: LocaleString;
  scoringIntro?: LocaleText;
  scoringReveal?: LocaleText;
  scoringStatus?: LocaleText;
  scoringPoints?: LocaleText;
};

export type Game = {
  _id: string;
  _type: "game";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mat?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  matTexture?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  courtierBack?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  whiteMissionBack?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blueMissionBack?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  pictogramFrame?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  arrowUp?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  arrowDown?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  paper?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Interface = {
  _id: string;
  _type: "interface";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  background?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  pattern?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decorTop?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  decorBottom?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  hero?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  hostIcon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  playerColors?: Array<string>;
  desktopOnly?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  minPlayers?: number;
  maxPlayers?: number;
  theme?: {
    background?: string;
    foreground?: string;
    accent?: string;
    surface?: string;
    surfaceDark?: string;
  };
  bodyFont?:
    | "Inter"
    | "Nunito"
    | "Fredoka"
    | "Baloo 2"
    | "Poppins"
    | "Outfit"
    | "DM Sans"
    | "Montserrat"
    | "Space Grotesk"
    | "Lilita One"
    | "Bangers"
    | "Bebas Neue"
    | "Cinzel"
    | "Playfair Display"
    | "Alegreya"
    | "Press Start 2P";
  displayFont?:
    | "Inter"
    | "Nunito"
    | "Fredoka"
    | "Baloo 2"
    | "Poppins"
    | "Outfit"
    | "DM Sans"
    | "Montserrat"
    | "Space Grotesk"
    | "Lilita One"
    | "Bangers"
    | "Bebas Neue"
    | "Cinzel"
    | "Playfair Display"
    | "Alegreya"
    | "Press Start 2P";
  bodyFontFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  displayFontFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  rulesPdfFrFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  rulesPdfEnFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  rulesPdfFr?: string;
  rulesPdfEn?: string;
  creditsAuthors?: string;
  publisher?: string;
  publisherUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Condition
  | SanityImageAssetReference
  | Mission
  | SanityImageCrop
  | SanityImageHotspot
  | LocaleText
  | FamilyReference
  | RoleReference
  | Courtier
  | Role
  | LocaleString
  | Family
  | Texts
  | LocaleStringList
  | Rules
  | Game
  | Interface
  | SanityFileAssetReference
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/sanity/queries.ts
// Variable: CATALOG_QUERY
// Query: {  "game": *[_id == "game"][0]{ mat, matTexture, courtierBack, whiteMissionBack, blueMissionBack, pictogramFrame, arrowUp, arrowDown },  "rules": *[_id == "rules"][0],  "texts": *[_id == "texts"][0]{ missionsButton, banquetStarts },  "families": *[_type == "family"]{ _id, name, key, color, pictogram },  "roles": *[_type == "role"]{ _id, name, key, countPerFamily, pictogram, rule, "lettering": lettering.asset->url },  "courtiers": *[_type == "courtier"]{ _id, quantity, card, "family": family->key, "role": role->key },  "missions": *[_type == "mission"]{ _id, color, text, card, condition }}
export type CATALOG_QUERY_RESULT = {
  game:
    | {
        mat: null;
        matTexture: null;
        courtierBack: null;
        whiteMissionBack: null;
        blueMissionBack: null;
        pictogramFrame: null;
        arrowUp: null;
        arrowDown: null;
      }
    | {
        mat: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        matTexture: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        courtierBack: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        whiteMissionBack: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        blueMissionBack: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        pictogramFrame: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        arrowUp: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        arrowDown: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
      }
    | null;
  rules:
    | {
        _id: "rules";
        _type: "courtier";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        family?: FamilyReference;
        role?: RoleReference;
        card?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        quantity?: number;
      }
    | {
        _id: "rules";
        _type: "family";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: LocaleString;
        key?: "butterfly" | "carp" | "hare" | "nightingale" | "stag" | "toad";
        color?: string;
        pictogram?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _id: "rules";
        _type: "game";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        mat?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        matTexture?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        courtierBack?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        whiteMissionBack?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        blueMissionBack?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        pictogramFrame?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        arrowUp?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        arrowDown?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        paper?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }
    | {
        _id: "rules";
        _type: "interface";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        background?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        pattern?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        decorTop?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        decorBottom?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        hero?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        hostIcon?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        playerColors?: Array<string>;
        desktopOnly?: boolean;
      }
    | {
        _id: "rules";
        _type: "mission";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        color?: "blue" | "white";
        text?: LocaleText;
        card?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        condition?: Condition;
      }
    | {
        _id: "rules";
        _type: "role";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: LocaleString;
        key?: "assassin" | "guard" | "noble" | "spy";
        countPerFamily?: number;
        pictogram?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        lettering?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        rule?: LocaleText;
      }
    | {
        _id: "rules";
        _type: "rules";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        videoId?: string;
        videoTitle?: LocaleString;
        goalTitle?: LocaleString;
        goalIntro?: LocaleText;
        goalFamilies?: LocaleText;
        goalMissions?: LocaleText;
        flowTitle?: LocaleString;
        flowIntro?: LocaleText;
        flowMat?: LocaleText;
        flowHand?: LocaleText;
        flowMissions?: LocaleText;
        flowStart?: LocaleText;
        turnTitle?: LocaleString;
        turnIntro?: LocaleText;
        turnTable?: LocaleText;
        turnDomain?: LocaleText;
        turnOpponent?: LocaleText;
        turnEnd?: LocaleText;
        rolesTitle?: LocaleString;
        rolesIntro?: LocaleText;
        scoringTitle?: LocaleString;
        scoringIntro?: LocaleText;
        scoringReveal?: LocaleText;
        scoringStatus?: LocaleText;
        scoringPoints?: LocaleText;
      }
    | {
        _id: "rules";
        _type: "sanity.fileAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "rules";
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      }
    | {
        _id: "rules";
        _type: "settings";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title?: string;
        description?: string;
        logo?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        minPlayers?: number;
        maxPlayers?: number;
        theme?: {
          background?: string;
          foreground?: string;
          accent?: string;
          surface?: string;
          surfaceDark?: string;
        };
        bodyFont?:
          | "Alegreya"
          | "Baloo 2"
          | "Bangers"
          | "Bebas Neue"
          | "Cinzel"
          | "DM Sans"
          | "Fredoka"
          | "Inter"
          | "Lilita One"
          | "Montserrat"
          | "Nunito"
          | "Outfit"
          | "Playfair Display"
          | "Poppins"
          | "Press Start 2P"
          | "Space Grotesk";
        displayFont?:
          | "Alegreya"
          | "Baloo 2"
          | "Bangers"
          | "Bebas Neue"
          | "Cinzel"
          | "DM Sans"
          | "Fredoka"
          | "Inter"
          | "Lilita One"
          | "Montserrat"
          | "Nunito"
          | "Outfit"
          | "Playfair Display"
          | "Poppins"
          | "Press Start 2P"
          | "Space Grotesk";
        bodyFontFile?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        displayFontFile?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        rulesPdfFrFile?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        rulesPdfEnFile?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        rulesPdfFr?: string;
        rulesPdfEn?: string;
        creditsAuthors?: string;
        publisher?: string;
        publisherUrl?: string;
      }
    | {
        _id: "rules";
        _type: "texts";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        tagline?: LocaleString;
        homeTitle?: LocaleString;
        homeIntro?: LocaleText;
        victoryPhrases?: LocaleStringList;
        ui_home?: {
          nicknamePlaceholder?: LocaleString;
          createButton?: LocaleString;
          joinButton?: LocaleString;
          chooseNickname?: LocaleString;
          codeLength?: LocaleString;
          linkCopied?: LocaleString;
          linkCopiedHint?: LocaleString;
          gameCreated?: LocaleString;
          codeLabel?: LocaleString;
          copyLink?: LocaleString;
        };
        ui_lobby?: {
          joinGameButton?: LocaleString;
          gameNotFound?: LocaleString;
          alreadyStarted?: LocaleString;
          backHome?: LocaleString;
          shareInvite?: LocaleString;
          playerCount?: LocaleString;
          you?: LocaleString;
          host?: LocaleString;
          startButton?: LocaleString;
          waitingPlayers?: LocaleString;
          waitingHost?: LocaleString;
        };
        ui_game?: {
          yourTurn?: LocaleString;
          turnOf?: LocaleString;
          yourTurnShort?: LocaleString;
          turnOfShort?: LocaleString;
          waiting?: LocaleString;
          gameOver?: LocaleString;
          leave?: LocaleString;
          replay?: LocaleString;
          desktopOnly?: LocaleString;
        };
        missionsButton?: LocaleString;
        banquetStarts?: LocaleString;
      }
    | null;
  texts:
    | {
        missionsButton: null;
        banquetStarts: null;
      }
    | {
        missionsButton: LocaleString | null;
        banquetStarts: LocaleString | null;
      }
    | null;
  families: Array<{
    _id: string;
    name: LocaleString | null;
    key: "butterfly" | "carp" | "hare" | "nightingale" | "stag" | "toad" | null;
    color: string | null;
    pictogram: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
  roles: Array<{
    _id: string;
    name: LocaleString | null;
    key: "assassin" | "guard" | "noble" | "spy" | null;
    countPerFamily: number | null;
    pictogram: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    rule: LocaleText | null;
    lettering: string | null;
  }>;
  courtiers: Array<{
    _id: string;
    quantity: number | null;
    card: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    family:
      "butterfly" | "carp" | "hare" | "nightingale" | "stag" | "toad" | null;
    role: "assassin" | "guard" | "noble" | "spy" | null;
  }>;
  missions: Array<{
    _id: string;
    color: "blue" | "white" | null;
    text: LocaleText | null;
    card: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    condition: Condition | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "game": *[_id == "game"][0]{ mat, matTexture, courtierBack, whiteMissionBack, blueMissionBack, pictogramFrame, arrowUp, arrowDown },\n  "rules": *[_id == "rules"][0],\n  "texts": *[_id == "texts"][0]{ missionsButton, banquetStarts },\n  "families": *[_type == "family"]{ _id, name, key, color, pictogram },\n  "roles": *[_type == "role"]{ _id, name, key, countPerFamily, pictogram, rule, "lettering": lettering.asset->url },\n  "courtiers": *[_type == "courtier"]{ _id, quantity, card, "family": family->key, "role": role->key },\n  "missions": *[_type == "mission"]{ _id, color, text, card, condition }\n}': CATALOG_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
